"""baseline

Revision ID: baseline
Revises: 
Create Date: 2026-08-31 20:48:36.338619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', 'admin', name='accountrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('subnets', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('health_port', sa.Integer(), nullable=False),
    sa.Column('scan_requested', sa.Boolean(), nullable=False),
    sa.Column('public_ip', sa.String(length=45), nullable=True),
    sa.Column('public_ip_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hosts', sa.Integer(), nullable=False),
    sa.Column('last_fingerprints', sa.Integer(), nullable=False),
    sa.Column('last_healthy', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_key_hash'), 'agents', ['key_hash'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('os_logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_logos_name'), 'os_logos', ['name'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wan_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wan_samples_timestamp'), 'wan_samples', ['timestamp'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', 'admin', name='accountrole'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_sessions_account_id'), 'auth_sessions', ['account_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.Enum('unknown', 'pc', 'laptop', 'server', 'phone', 'voip', 'tablet', 'ereader', 'wearable', 'tv', 'projector', 'media', 'display', 'console', 'speaker', 'router', 'ap', 'hub', 'iot', 'thermostat', 'appliance', 'vacuum', 'camera', 'doorbell', 'printer', 'nas', 'car', name='devicetype'), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('os_guess', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('overrides', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'ignored', name='approvalstatus'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('counts_for_presence', sa.Boolean(), nullable=False),
    sa.Column('notify_policy', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_approval_status'), 'devices', ['approval_status'], unique=False)
    op.create_index(op.f('ix_devices_is_online'), 'devices', ['is_online'], unique=False)
    op.create_table('enrolment_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['used_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrolment_tokens_token_hash'), 'enrolment_tokens', ['token_hash'], unique=True)
    op.create_table('connection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conn_history_device_ts', 'connection_history', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_connection_history_device_id'), 'connection_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_connection_history_timestamp'), 'connection_history', ['timestamp'], unique=False)
    op.create_table('device_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_images_device_id'), 'device_images', ['device_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('info', 'success', 'warning', 'alert', name='eventlevel'), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_ip_address')
    )
    op.create_index(op.f('ix_ip_addresses_address'), 'ip_addresses', ['address'], unique=False)
    op.create_index(op.f('ix_ip_addresses_device_id'), 'ip_addresses', ['device_id'], unique=False)
    op.create_table('mac_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=17), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('is_random', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', name='uq_mac_address')
    )
    op.create_index(op.f('ix_mac_addresses_address'), 'mac_addresses', ['address'], unique=False)
    op.create_index(op.f('ix_mac_addresses_device_id'), 'mac_addresses', ['device_id'], unique=False)
    op.create_table('open_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'port', name='uq_device_port')
    )
    op.create_index(op.f('ix_open_ports_device_id'), 'open_ports', ['device_id'], unique=False)
    op.create_table('pending_wakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac')
    )
    op.create_index(op.f('ix_pending_wakes_requested_at'), 'pending_wakes', ['requested_at'], unique=False)
    op.create_table('topology_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('local_device_id', sa.Integer(), nullable=True),
    sa.Column('local_label', sa.String(length=255), nullable=False),
    sa.Column('local_port', sa.String(length=120), nullable=True),
    sa.Column('remote_label', sa.String(length=255), nullable=False),
    sa.Column('remote_port', sa.String(length=120), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_edges_agent_id'), 'topology_edges', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_edges_agent_id'), table_name='topology_edges')
    op.drop_table('topology_edges')
    op.drop_index(op.f('ix_pending_wakes_requested_at'), table_name='pending_wakes')
    op.drop_table('pending_wakes')
    op.drop_index(op.f('ix_open_ports_device_id'), table_name='open_ports')
    op.drop_table('open_ports')
    op.drop_index(op.f('ix_mac_addresses_device_id'), table_name='mac_addresses')
    op.drop_index(op.f('ix_mac_addresses_address'), table_name='mac_addresses')
    op.drop_table('mac_addresses')
    op.drop_index(op.f('ix_ip_addresses_device_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_address'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_device_images_device_id'), table_name='device_images')
    op.drop_table('device_images')
    op.drop_index(op.f('ix_connection_history_timestamp'), table_name='connection_history')
    op.drop_index(op.f('ix_connection_history_device_id'), table_name='connection_history')
    op.drop_index('ix_conn_history_device_ts', table_name='connection_history')
    op.drop_table('connection_history')
    op.drop_index(op.f('ix_enrolment_tokens_token_hash'), table_name='enrolment_tokens')
    op.drop_table('enrolment_tokens')
    op.drop_index(op.f('ix_devices_is_online'), table_name='devices')
    op.drop_index(op.f('ix_devices_approval_status'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_auth_sessions_account_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_wan_samples_timestamp'), table_name='wan_samples')
    op.drop_table('wan_samples')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_os_logos_name'), table_name='os_logos')
    op.drop_table('os_logos')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_agents_key_hash'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
